name: Build Quasar

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

# This workflow makes x86_64 binaries for linux.
# TODO: add darwin later
jobs:
  build-go:
    name: quasar-${{ matrix.targetos }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        targetos: [ linux ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.rs
            **/**.go
            go.mod
            go.sum
            Makefile
            .github/workflows/build.yml
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.7
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
      - name: Display go version
        if: env.GIT_DIFF
        run: go version
      - name: Build quasarnoded
        if: env.GIT_DIFF
        run: make build-reproducible-${{ matrix.arch }}
      - uses: actions/upload-artifact@v3
        if: env.GIT_DIFF
        with:
          name: quasarnoded-${{ matrix.targetos }}-${{ matrix.arch }}
          path: build/quasarnoded-${{ matrix.targetos }}-${{ matrix.arch }}
  build-rust:
    name: quasar-contracts-${{ matrix.targetos }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        targetos: [linux ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.rs
            Makefile
            .github/workflows/build.yml
      - name: Build smart contracts
        if: env.GIT_DIFF
        run: make compile-wasm-artifacts
      - uses: actions/upload-artifact@v3
        if: env.GIT_DIFF
        with:
          name: smart-contracts
          path: |
            smart-contracts/artifacts/basic_vault.wasm
            smart-contracts/artifacts/lp_strategy.wasm
