name: Lint Quasar code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

# This workflow makes x86_64 binaries for linux.
# TODO: add darwin later
jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.7
      - name: Display go version
        run: go version
      - name: Go lint
        run: make lint
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.rs
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Show versions
        run: rustc -V && cargo -V
      - name: Rust lint
        run: cd smart-contracts && RUSTFLAGS="-Dwarnings" cargo clippy --workspace -- -D warnings --A deprecated 
      - name: Rust format check
        run: cd smart-contracts && cargo fmt --all -- --check
