name: Test Quasar

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Display go version
        run: go version
      - name: Run all tests
        run: make test-cover
      - name: Code coverage report
        uses: codecov/codecov-action@v1.5.2
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run unit-tests
        run: cd smart-contracts && cargo test --lib
      - name: Run vault-tests
        run: cd smart-contracts && cargo test --lib -p basic-vault
  test-e2e:
    needs: [test-go, test-rust]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker e2e build
        run: make docker-e2e-build quasar osmosis
      - name: Build smart contracts
        run: make compile-wasm-artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: smart-contracts
          path: |
            smart-contracts/artifacts/basic_vault.wasm
            smart-contracts/artifacts/lp_strategy.wasm
      - name: Run e2e tests
        run: cd tests/e2e && make test-e2e-parallel